// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mKCH3BBHL5q2ZUQXDXcEu3
// Component: nCk1A11gO3Ta
import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  hasVariant
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import Button from "../../Button"; // plasmic-import: vWxSn1gCvyi9/component
import { useScreenVariants as useScreenVariantscJt4ICnSXdeA } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: cJT4ICnSXdeA/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: mKCH3BBHL5q2ZUQXDXcEu3/projectcss
import sty from "./PlasmicHomepage2.module.css"; // plasmic-import: nCk1A11gO3Ta/css
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: _ucDmUpBe5BU/icon
import Icon8Icon from "./icons/PlasmicIcon__Icon8"; // plasmic-import: keYcx2-wVW3z/icon
import Icon13Icon from "./icons/PlasmicIcon__Icon13"; // plasmic-import: 9c2kirVgfor4/icon
import Icon10Icon from "./icons/PlasmicIcon__Icon10"; // plasmic-import: LgqgdAqymtEM/icon
import Icon11Icon from "./icons/PlasmicIcon__Icon11"; // plasmic-import: XkAkyJEqWnR8/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: pe1sy_8-ouO2/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: s3dloteqoK4_/icon
import Icon28Icon from "./icons/PlasmicIcon__Icon28"; // plasmic-import: Sbmgn129xLUW/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: NzKZBDH4Pk7X/icon

createPlasmicElementProxy;

export const PlasmicHomepage2__VariantProps = new Array();

export const PlasmicHomepage2__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomepage2__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantscJt4ICnSXdeA()
  });
  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <Stack__
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__zz5Sv)}>
            <div
              data-plasmic-name={"container3"}
              data-plasmic-override={overrides.container3}
              className={classNames(projectcss.all, sty.container3)}
            >
              <div
                data-plasmic-name={"row"}
                data-plasmic-override={overrides.row}
                className={classNames(projectcss.all, sty.row)}
              >
                <div className={classNames(projectcss.all, sty.column__aXlka)}>
                  <PlasmicLink__
                    data-plasmic-name={"headerLeft"}
                    data-plasmic-override={overrides.headerLeft}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.headerLeft
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__leLb0)}
                      displayHeight={"67px"}
                      displayMaxHeight={"74px"}
                      displayMaxWidth={"199px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"auto"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/tutorial_app_in_5_minutes/images/logoPlasmicNewSvg.svg",
                        fullWidth: 300,
                        fullHeight: 113,
                        aspectRatio: 2.662651
                      }}
                    />
                  </PlasmicLink__>
                </div>
                <div className={classNames(projectcss.all, sty.column__pKsnk)}>
                  <div
                    data-plasmic-name={"headerRight"}
                    data-plasmic-override={overrides.headerRight}
                    className={classNames(projectcss.all, sty.headerRight)}
                  >
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__lQPao
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Services"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__oeop6
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Stories"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__vUaR
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"About us"}
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__vN08R
                      )}
                      component={Link}
                      platform={"nextjs"}
                    >
                      {"Contact us"}
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div
            data-plasmic-name={"hero"}
            data-plasmic-override={overrides.hero}
            className={classNames(projectcss.all, sty.hero)}
          >
            <div
              data-plasmic-name={"container7"}
              data-plasmic-override={overrides.container7}
              className={classNames(projectcss.all, sty.container7)}
            >
              <div
                data-plasmic-name={"row3"}
                data-plasmic-override={overrides.row3}
                className={classNames(projectcss.all, sty.row3)}
              >
                <div
                  data-plasmic-name={"info"}
                  data-plasmic-override={overrides.info}
                  className={classNames(projectcss.all, sty.info)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___671Zi)}
                  >
                    <h1
                      data-plasmic-name={"h1"}
                      data-plasmic-override={overrides.h1}
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1
                      )}
                    >
                      {"Choose us for marketing photography"}
                    </h1>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__x83X6
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt."
                      }
                    </div>
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__pl8VB
                      )}
                      color={"blackCoffee"}
                      endIcon={
                        <CheckSvgIcon
                          className={classNames(
                            projectcss.all,
                            sty.svg___1910Q
                          )}
                          role={"img"}
                        />
                      }
                      startIcon={
                        <CheckSvgIcon
                          className={classNames(projectcss.all, sty.svg__pnwU)}
                          role={"img"}
                        />
                      }
                      submitsForm={true}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3HraP
                        )}
                      >
                        {hasVariant(globalVariants, "screen", "mobileOnly")
                          ? "Get In touch"
                          : "Get In touch"}
                      </div>
                    </Button>
                  </Stack__>
                </div>
                <div
                  data-plasmic-name={"fig"}
                  data-plasmic-override={overrides.fig}
                  className={classNames(projectcss.all, sty.fig)}
                />
              </div>
            </div>
          </div>
          <section className={classNames(projectcss.all, sty.section__kdW0P)}>
            <div className={classNames(projectcss.all, sty.freeBox__dwNjv)}>
              <div className={classNames(projectcss.all, sty.freeBox__waW6K)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__vBjsS)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__gsXIm
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Why Choose Us"
                      : "Why choose us"}
                  </h2>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__ykDot)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__rO1JF)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__r0Ug9
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__tpdLd
                          )}
                        >
                          <Icon8Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__fI4O9
                            )}
                            role={"img"}
                          />
                        </div>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__emdC7
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__vHDmg
                            )}
                          >
                            {"Welcoming  trusted"}
                          </h3>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__oScPi
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                            }
                          </div>
                        </Stack__>
                      </Stack__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__hpztP)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___45F8H
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__poiGg
                          )}
                        >
                          <Icon13Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___8HYsc
                            )}
                            role={"img"}
                          />
                        </div>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__rW74R
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3___4Nyet
                            )}
                          >
                            {"Tested and secure"}
                          </h3>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__syRBg
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                            }
                          </div>
                        </Stack__>
                      </Stack__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__lh3Zj)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__skiE
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hrHlh
                          )}
                        >
                          <Icon10Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___07FSh
                            )}
                            role={"img"}
                          />
                        </div>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__tVy2D
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__ayNz6
                            )}
                          >
                            {"Mindful notifications"}
                          </h3>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__aSuz
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                            }
                          </div>
                        </Stack__>
                      </Stack__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__qNg57)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vZhY
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__dqub3
                          )}
                        >
                          <Icon11Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__yNadi
                            )}
                            role={"img"}
                          />
                        </div>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___0OQme
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__w87Nj
                            )}
                          >
                            {"Real-time results"}
                          </h3>
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__g7Ur
                            )}
                          >
                            {
                              "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor ."
                            }
                          </div>
                        </Stack__>
                      </Stack__>
                    </div>
                  </Stack__>
                </Stack__>
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__h1Mpr)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__jsIcW)}
            >
              <div className={classNames(projectcss.all, sty.column__jPtr4)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__bf98Z)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tutorial_app_in_5_minutes/images/girls18285391920Jpg.jpg",
                    fullWidth: 1920,
                    fullHeight: 1280,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.column__x4Ya)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__lQhDc)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2___6NmCf
                    )}
                  >
                    {"The standard used since"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mxYo4
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___4F8Su
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__xubdK)}
                    color={"blackCoffee"}
                    endIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__rvSXp)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__ijR5V)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jzf74
                      )}
                    >
                      {"About Us"}
                    </div>
                  </Button>
                </Stack__>
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__oL2GP)}>
              <div className={classNames(projectcss.all, sty.freeBox__aGw6G)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__ao2J0)}
                />
              </div>
            </div>
          </section>
          <section className={classNames(projectcss.all, sty.section__fgge9)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__yvTl2)}
            >
              <div className={classNames(projectcss.all, sty.column__s6QZt)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__br2Af)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__vgSwi
                    )}
                  >
                    {"The standard used since"}
                  </h2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dmKiE
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
                    }
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lYhZs
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
                    }
                  </div>
                  <Button
                    className={classNames("__wab_instance", sty.button__fYx3I)}
                    color={"blackCoffee"}
                    endIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__kfflb)}
                        role={"img"}
                      />
                    }
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__pLnUx)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cRqfd
                      )}
                    >
                      {"Contact Us"}
                    </div>
                  </Button>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.column__m0C1M)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__bXtls)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"100%"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/tutorial_app_in_5_minutes/images/people31046351920Jpg.jpg",
                    fullWidth: 1920,
                    fullHeight: 1281,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__baovH)}>
              <div className={classNames(projectcss.all, sty.freeBox__inkc9)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__iiRo1)}
                />
              </div>
            </div>
          </section>
          <div className={classNames(projectcss.all, sty.freeBox__yjMrs)}>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__bFdpe)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__yQb82)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__oVgjL)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dz9Bf
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
                    }
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___2LEs)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__onEs)}
                    displayHeight={"64px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"64px"}
                    src={{
                      src: "/plasmic/tutorial_app_in_5_minutes/images/woman32879561920Jpg.jpg",
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__br1SV)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__zRcXx)}
                    >
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__hr9Pw
                        )}
                      >
                        {"Lorem doi"}
                      </h5>
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__pHr6L)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__dS2QC)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lkEon
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
                    }
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__ocMju)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img___4Ro0)}
                    displayHeight={"64px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"64px"}
                    src={{
                      src: "/plasmic/tutorial_app_in_5_minutes/images/people31046351920Jpg.jpg",
                      fullWidth: 1920,
                      fullHeight: 1281,
                      aspectRatio: undefined
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__n6FsE)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__xGo30)}
                    >
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5__nWsxo
                        )}
                      >
                        {"Lorem doi"}
                      </h5>
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__kuQRe)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__dhhzx)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___2RXjQ
                    )}
                  >
                    {
                      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam"
                    }
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__bLt26)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__yb31U)}
                    displayHeight={"64px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"64px"}
                    src={{
                      src: "/plasmic/tutorial_app_in_5_minutes/images/girls18285391920Jpg.jpg",
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />

                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__vllCn)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__gOeHb)}
                    >
                      <h5
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.h5___625Mn
                        )}
                      >
                        {"Lorem doi"}
                      </h5>
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
          </div>
          <div
            data-plasmic-name={"companiesSection"}
            data-plasmic-override={overrides.companiesSection}
            className={classNames(projectcss.all, sty.companiesSection)}
          >
            <Stack__
              as={"div"}
              data-plasmic-name={"container2"}
              data-plasmic-override={overrides.container2}
              hasGap={true}
              className={classNames(projectcss.all, sty.container2)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__zkutM
                )}
              >
                {"We work with local businesses"}
              </h2>
              <div className={classNames(projectcss.all, sty.freeBox___8J4QM)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___6RjDh)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__gueZf)}
                    displayHeight={"48px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={
                      "https://plasmic-ray.s3.us-west-2.amazonaws.com/logo-strapi.svg"
                    }
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__ejOfy)}
                    displayHeight={"48px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={
                      "https://plasmic-ray.s3.us-west-2.amazonaws.com/logo-segment.svg"
                    }
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__yQtJe)}
                    displayHeight={"48px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={
                      "https://plasmic-ray.s3.us-west-2.amazonaws.com/logo-xstate.svg"
                    }
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__cz7C5)}
                    displayHeight={"48px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    src={
                      "https://plasmic-ray.s3.us-west-2.amazonaws.com/logo-mapbox.svg"
                    }
                  />
                </Stack__>
              </div>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__gkXCr)}>
            <Stack__
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(projectcss.all, sty.container)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__ssJvL
                )}
              >
                {"Make a call to action."}
              </h2>
              <Button
                className={classNames("__wab_instance", sty.button__qEyfN)}
                color={"blackCoffee"}
                endIcon={
                  <CheckSvgIcon
                    className={classNames(projectcss.all, sty.svg__bmr5)}
                    role={"img"}
                  />
                }
                startIcon={
                  <CheckSvgIcon
                    className={classNames(projectcss.all, sty.svg__jCqaO)}
                    role={"img"}
                  />
                }
                submitsForm={true}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__h1Ysq
                  )}
                >
                  {"Get In Touch"}
                </div>
              </Button>
            </Stack__>
          </div>
          <div className={classNames(projectcss.all, sty.freeBox__ipUqZ)}>
            <div className={classNames(projectcss.all, sty.freeBox__zoqZf)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__faP0)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__qdyB9)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___9Yig5)}
                  >
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__vZut6
                      )}
                    >
                      {"Company Name"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oivw
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>
                          {"This site proudly built in "}
                        </React.Fragment>
                        {
                          <PlasmicLink__
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              projectcss.plasmic_default__inline,
                              sty.link___4IQqU
                            )}
                            component={Link}
                            href={"https://www.plasmic.app"}
                            platform={"nextjs"}
                          >
                            {"Plasmic"}
                          </PlasmicLink__>
                        }
                        <React.Fragment>{"."}</React.Fragment>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lir0
                      )}
                    >
                      {"Connect with us"}
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__jg41D)}
                    >
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__ksAEt
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon3Icon
                          className={classNames(projectcss.all, sty.svg__k1S51)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link___44CBv
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon4Icon
                          className={classNames(projectcss.all, sty.svg__yghJc)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                      <PlasmicLink__
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          sty.link__r7Usj
                        )}
                        component={Link}
                        href={"#"}
                        platform={"nextjs"}
                        target={"_blank"}
                      >
                        <Icon28Icon
                          className={classNames(projectcss.all, sty.svg__mS)}
                          role={"img"}
                        />
                      </PlasmicLink__>
                    </Stack__>
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__jYUp)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__vGAb
                    )}
                  >
                    {"Photography"}
                  </h3>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__gp6K7
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon5Icon
                        className={classNames(projectcss.all, sty.svg__ef3Pm)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__f8XyT
                      )}
                    >
                      {"Services"}
                    </div>
                    {false ? (
                      <Icon5Icon
                        className={classNames(projectcss.all, sty.svg__nzyY)}
                        role={"img"}
                      />
                    ) : null}
                  </Stack__>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__tWsOc
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon5Icon
                        className={classNames(projectcss.all, sty.svg__io5Hz)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dTBjS
                      )}
                    >
                      {"Stories"}
                    </div>
                    {false ? (
                      <Icon5Icon
                        className={classNames(projectcss.all, sty.svg___6AVii)}
                        role={"img"}
                      />
                    ) : null}
                  </Stack__>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__f1O)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__hay3L
                    )}
                  >
                    {"Company"}
                  </h3>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__axyx3
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon5Icon
                        className={classNames(projectcss.all, sty.svg__g3Pl)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mYr
                      )}
                    >
                      {"Contact us"}
                    </div>
                    {false ? (
                      <Icon5Icon
                        className={classNames(projectcss.all, sty.svg__cod8H)}
                        role={"img"}
                      />
                    ) : null}
                  </Stack__>
                  <Stack__
                    as={PlasmicLink__}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__dgWM
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon5Icon
                        className={classNames(projectcss.all, sty.svg___6NyIl)}
                        role={"img"}
                      />
                    ) : null}
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__b2UzT
                      )}
                    >
                      {"About us"}
                    </div>
                    {false ? (
                      <Icon5Icon
                        className={classNames(projectcss.all, sty.svg__xwoH)}
                        role={"img"}
                      />
                    ) : null}
                  </Stack__>
                </Stack__>
              </Stack__>
            </div>
          </div>
        </Stack__>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "container3",
    "row",
    "headerLeft",
    "headerRight",
    "hero",
    "container7",
    "row3",
    "info",
    "h1",
    "fig",
    "companiesSection",
    "container2",
    "container"
  ],

  container3: ["container3", "row", "headerLeft", "headerRight"],
  row: ["row", "headerLeft", "headerRight"],
  headerLeft: ["headerLeft"],
  headerRight: ["headerRight"],
  hero: ["hero", "container7", "row3", "info", "h1", "fig"],
  container7: ["container7", "row3", "info", "h1", "fig"],
  row3: ["row3", "info", "h1", "fig"],
  info: ["info", "h1"],
  h1: ["h1"],
  fig: ["fig"],
  companiesSection: ["companiesSection", "container2"],
  container2: ["container2"],
  container: ["container"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage2__ArgProps,
          internalVariantPropNames: PlasmicHomepage2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage2";
  } else {
    func.displayName = `PlasmicHomepage2.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage2 = Object.assign(
  // Top-level PlasmicHomepage2 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    container3: makeNodeComponent("container3"),
    row: makeNodeComponent("row"),
    headerLeft: makeNodeComponent("headerLeft"),
    headerRight: makeNodeComponent("headerRight"),
    hero: makeNodeComponent("hero"),
    container7: makeNodeComponent("container7"),
    row3: makeNodeComponent("row3"),
    info: makeNodeComponent("info"),
    h1: makeNodeComponent("h1"),
    fig: makeNodeComponent("fig"),
    companiesSection: makeNodeComponent("companiesSection"),
    container2: makeNodeComponent("container2"),
    container: makeNodeComponent("container"),
    // Metadata about props expected for PlasmicHomepage2
    internalVariantProps: PlasmicHomepage2__VariantProps,
    internalArgProps: PlasmicHomepage2__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage2;
/* prettier-ignore-end */
